# Welcome to Jupyter!

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook

In [1]:
conda install ipython jupyter

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/conda/envs/notebook

  added / updated specs:
    - ipython
    - jupyter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.5.30  |       ha878542_0         136 KB  conda-forge
    certifi-2021.5.30          |   py36h5fab9bb_0         141 KB  conda-forge
    jupyter-1.0.0              |   py36h5fab9bb_6           6 KB  conda-forge
    jupyter_console-6.4.0      |     pyhd8ed1ab_0          22 KB  conda-forge
    openssl-1.1.1k             |       h7f98852_0         2.1 MB  conda-forge
    prompt-toolkit-3.0.19      |     pyha770c72_0         244 KB  conda-forge
    prompt_toolkit-3.0.19      |       hd8ed1ab_0           4 KB  

In [7]:
def i(a):
    print(a)
    

In [1]:
i('avestruz e ameba')

NameError: name 'i' is not defined

In [1]:
import numpy as np
data=np.random.randn(2,3)
data
data.dtype

dtype('float64')

In [2]:
import numpy as np
l=[[112,15,661,43],[1,661,909,5]]
data2=np.array(l)
data2.dtype

dtype('int64')

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.empty((2,3,2,4))

array([[[[ 4.68225268e-310,  0.00000000e+000,  6.94315985e-310,
           6.94315985e-310],
         [-2.24620258e+070,  6.94315985e-310,  6.94315985e-310,
          -2.58227421e+307]],

        [[ 6.94315985e-310,  6.94315985e-310,  1.16190637e+117,
           6.94315985e-310],
         [ 6.94315985e-310, -2.33794073e-161,  6.94315985e-310,
           6.94315985e-310]],

        [[-1.87452501e+062,  6.94315985e-310,  6.94315985e-310,
          -3.43765718e+017],
         [ 6.94315985e-310,  6.94315985e-310, -2.13048127e+286,
           6.94315985e-310]]],


       [[[ 6.94315985e-310, -1.11166815e-025,  6.94315985e-310,
           6.94315985e-310],
         [ 2.86844885e+206,  6.94315985e-310,  6.94315985e-310,
           1.34735047e+172]],

        [[ 6.94315985e-310,  6.94315985e-310, -2.68543676e-094,
           6.94315985e-310],
         [ 6.94315985e-310,  4.21636870e+164,  6.94315985e-310,
           6.94315985e-310]],

        [[-7.98337347e-132,  6.94315985e-310,  6.94315985e

In [3]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [11]:

a=np.array([1,31,54,7])
a.astype(np.float64).astype(np.int16)

array([ 1, 31, 54,  7], dtype=int16)

In [23]:
b=np.array(['41', '31','21'], dtype=np.string_)
b.astype(float)

array([41., 31., 21.])

In [30]:
int_array=np.arange(10)
calibers=np.array([0.33,0.54,0.76,0.99])
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
arr=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[0,0,0],[100,400,500]])
arr2>arr

array([[False, False, False],
       [ True,  True,  True]])

In [2]:
arr=np.array([1,2,4,5,6])
arr[2]

4

In [6]:
arr=np.arange(6).reshape(3,2)
arr.T

array([[0, 2, 4],
       [1, 3, 5]])

In [35]:
one=np.array([[[1,2,9,5],[3,4,6,8]],[[4,7,1,12],[12,76,45,31]]])
two=np.array([[5,6],[7,8]])
print(one)
one.transpose(0,2,1)

[[[ 1  2  9  5]
  [ 3  4  6  8]]

 [[ 4  7  1 12]
  [12 76 45 31]]]


array([[[ 1,  3],
        [ 2,  4],
        [ 9,  6],
        [ 5,  8]],

       [[ 4, 12],
        [ 7, 76],
        [ 1, 45],
        [12, 31]]])

In [1]:
import numpy as np
a=np.array([[1.43,4.12],[9.01,25.009]])
b=np.array([[3,9],[54,6]])
c=np.array([[99,81],[0,0]])

np.greater(a,b)

array([[False, False],
       [False,  True]])

In [18]:
a=np.array([3,8,3,4])
b=np.array([4,6,7,8])
x,y=np.meshgrid(a,b)
np.sqrt(x**2+y**2)

array([[ 5.        ,  8.94427191,  5.        ,  5.65685425],
       [ 6.70820393, 10.        ,  6.70820393,  7.21110255],
       [ 7.61577311, 10.63014581,  7.61577311,  8.06225775],
       [ 8.54400375, 11.3137085 ,  8.54400375,  8.94427191]])

In [126]:

a=np.random.randn(4,4)
b=np.array([3,4])
c=np.array([True,False])

#print(a if c else b)
np.where(a>0,1,a)

array([[-1.2804808 ,  1.        ,  1.        , -0.18912661],
       [ 1.        , -0.79959737,  1.        ,  1.        ],
       [-0.04452774,  1.        , -0.10387056, -1.75633065],
       [-0.20498457, -0.69218013,  1.        ,  1.        ]])

In [2]:
x = np.array([[[0,1],[2,3]],
              [[4,5],[6,7]]])
np.swapaxes(x,0,2)


array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [36]:
import numpy as np
a=np.array([[0,-5],[-1,-20],[5,6]])
a.sort()
a

array([[ -5,   0],
       [-20,  -1],
       [  5,   6]])

In [51]:
a=np.array([1,2,3,5,1,4,1])
b=np.array([1,92,2])
np.setxor1d(b,a)


array([ 3,  4,  5, 92])

In [77]:
o=np.array([[1,3],[1,0]])
p=np.array([[1,1],[1,1]] )


In [90]:
from numpy.linalg import qr, inv
inv(o)

array([[ 0.        ,  1.        ],
       [ 0.33333333, -0.33333333]])

In [127]:
a=np.random.randn(4).reshape(2,2)
b=np.random.normal(size=(2,2))
np.random.binomial(-1,2)

ValueError: p < 0, p > 1 or p is NaN

In [1]:
import numpy as np
a=np.random.randint(0,2,size=1000)
steps=np.where(a>0,1,-1)
walk=steps.cumsum()
x=np.abs(walk>10).argmax()
print(x,walk)


0 [ -1   0   1   0  -1   0  -1  -2  -1   0  -1  -2  -3  -2  -3  -2  -3  -4
  -3  -2  -1  -2  -1   0   1   0  -1  -2  -3  -4  -5  -6  -7  -6  -5  -4
  -5  -6  -7  -6  -7  -8  -7  -8  -7  -6  -7  -8  -7  -8  -9 -10 -11 -10
  -9  -8  -7  -6  -7  -8  -9 -10 -11 -12 -11 -10  -9  -8  -9 -10  -9 -10
  -9 -10 -11 -12 -13 -14 -15 -16 -17 -18 -19 -18 -19 -20 -21 -22 -21 -20
 -19 -20 -21 -22 -23 -22 -21 -22 -21 -22 -21 -20 -21 -22 -23 -22 -23 -24
 -25 -24 -23 -24 -23 -22 -21 -20 -19 -18 -19 -18 -17 -16 -15 -16 -15 -14
 -13 -14 -15 -14 -13 -12 -13 -12 -13 -12 -11 -12 -13 -12 -13 -14 -15 -14
 -13 -12 -11 -12 -13 -12 -11 -12 -13 -12 -11 -10  -9  -8  -9  -8  -9 -10
 -11 -12 -11 -12 -11 -12 -11 -10 -11 -12 -11 -12 -13 -12 -13 -14 -13 -12
 -13 -14 -15 -16 -15 -14 -15 -14 -15 -14 -13 -12 -11 -12 -13 -14 -13 -12
 -11 -10 -11 -12 -13 -12 -13 -14 -13 -14 -15 -14 -15 -14 -15 -16 -17 -16
 -15 -14 -13 -12 -11 -10 -11 -12 -11 -10 -11 -12 -11 -12 -11 -10  -9  -8
  -9  -8  -7  -6  -7  -6  -5  -4  -5  -4  -5  -4 

In [17]:
import numpy as np
a=np.random.randint(0,2,size=(5000,1000))
steps=np.where(a>0,1,-1)
walks=steps.cumsum(1)
hits30=(np.abs(walks)>=30).any(1)
(np.abs(walks[hits30])>=30).argmax(1)                        .mean()

503.1646234676007

In [48]:
ma=np.array([[2,3,8,16],[1,2,5,9]])
cond=(np.abs(ma)>2).any(1)
#(np.abs(ma[cond])>2).argmax(1).mean()
(np.abs(ma)>3)

array([[False, False,  True,  True],
       [False, False,  True,  True]])